name: ac_dart
description: AnyCode Dart services and extensions
version: 0.1.3
homepage: https://github.com/anycode/ac_dart.dart
repository: https://github.com/anycode/ac_dart.dart
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cross_file: ^0.3.3+8
  intl: ^0.19.0
  json_annotation: ^4.8.1
  latlong2: ^0.9.0
  logger: ^2.0.2+1
  logging: ^1.2.0
  media_storage: ^0.0.1
  meta: ^1.10.0
  package_info_plus: ^5.0.1
  path: ^1.9.0
  path_provider: ^2.1.2
  ranges:
    #path: ../../../../dart/lib/ranges
    git:
      url: https://github.com/anycode/ac_ranges.dart.git
      ref: v3.0.7
  uuid: ^4.3.3

dev_dependencies:
  test: ^1.25.2
  lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
